url: https://NickGraham.github.io
baseurl:

# Site settings
title: Nick Graham
email: nj_graham@sky.com
description: "A portfolio of Nick's projects, and experiences."


# Team names, titles and social links
people:
- name: Eddie Cheung
  pic: 1
  position: Lead Accountant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Nick Graham
  pic: 2
  position: CEO & Design Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/nicholas-graham-165a9210a/

- name: Ben Youell
  pic: 3
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/nick-graham-ceng-165a9210a/
  - title: github
    url: http://github.com/lilNickyg

# Postal address (add as many lines as necessary)
address:
  - line:
  - line: UK

# Build settings
markdown: kramdown
permalink: pretty
