url: https://lilNickyg.github.io
baseurl: 

# Site settings
title: BeNickEd
email: ilovehearthstone@hotmail.com
description: "BeNickEd is a nameplace for Nick's projects and business ideas. Any exciting plans ideas and projects I'm working on will be posted here."


# Team names, titles and social links
people:
- name: Eddie Cheung
  pic: 1
  position: Lead Accountant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Nick Graham
  pic: 2
  position: CEO & Design Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/nicholas-graham-165a9210a/

- name: Ben Youell
  pic: 3
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/lilNickyg

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Bracknell, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
